spring:
  application:
    name: coffee-machine

  datasource:
      url: jdbc:postgresql://localhost:5432/coffeemachine
      username: postgres
      password: postgres
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true

springdoc:
  api-docs:
    path: /api-docs

server:
  port: 8080